# check source, ensure destination directory exists, copy ert, copy key
# vars:
# src_cert
# dest_cert

- name: assert that vars are well defined
  assert:
    that:
    - cert_name is defined
    - cert_ca_common_name is defined
    - cert_path is defined
    - cert_dest_dir is defined
    quiet: true
  
- name: Ensure destination directories exist
  ansible.builtin.file:
    path: "{{ cert_dest_dir }}"
    state: directory
    mode: '0700' # Adjust permissions as needed for security

- name: put certificate keys in place
  copy:
    src: "{{ cert_path }}/{{ cert_ca_common_name }}/subject_keys/{{ cert_name }}.pem"
    dest: "{{ cert_dest_dir }}/{{ cert_name }}.key"

- name: put certificates in place
  copy:
    src: "{{ cert_path }}/{{ my_certs.conf.ca_common_name }}/certs/{{ cert_name }}.crt"
    dest: "{{ cert_dest_dir }}/{{ cert_name }}.crt"

