# processes recursively a given folder and templates all files from source to destination    
# variables:
# - template_source_dir (mandatory)
#     one of the following is mandatory too, either a given destination is used or a random one is created and returned
# - destination_dir: fixed destination, files will be moved there if variable is set
# - dir_var: return parameter with output directory, esp. for random locations
# - title: prefix for the string of the name
# - owner:
# - group:
# - directoryMode:
# - fileMode:

- name: verify if variables are sufficiently defined
  assert:
    that:
    - destination_dir is defined or dir_var is defined
    - template_source_dir is defined
    quiet: true

- block:
  - name: create remote temporary directory 
    ansible.builtin.tempfile:
      state: directory
      suffix: "_template_remote"
    register: remote_tmp_dir
    changed_when: false
    when: destination_dir is not defined

  - name: "{{ title | default('') }} get template directories"
    find:
      path: "{{ template_source_dir }}"
      file_type: directory
    register: template_dirs_found
    delegate_to: localhost

  - name: set vars
    vars: 
      effective_dest_dir: "{{ destination_dir if destination_dir is defined else remote_tmp_dir.path }}"
    set_fact:
      templates_dirs: "{{ (template_dirs_found.files | map(attribute='path') | list) + [template_source_dir] }}"
      templates_files: "{{ lookup('pipe', '[ ! -d \"'+ template_source_dir +'\" ] || find \"'+ template_source_dir +'\" ! -type d').split('\n')|reject('match', '^$')  }}"
      "{{ dir_var|default('foo') }}": "{{ effective_dest_dir }}"
      dest_dir: "{{ effective_dest_dir }}"

  - name: "{{ title | default('') }} ensure destination directories exist for templates"
    become: no
    file:
      path: "{{ dest_dir }}/{{ item | relpath(template_source_dir) }}"
      state: directory
      owner: "{{ owner|default('root') }}"
      group: "{{ group|default('root') }}"
      mode: "{{ directoryMode|default('0755') }}"
    loop: "{{ templates_dirs }}"
    tags:
    - molecule-idempotence-notest

  - name: render templates
    become: no
    template:
      src: "{{ item }}"
      dest: "{{ dest_dir }}/{{ item | relpath(template_source_dir) }}"
      owner: "{{ owner|default('root') }}"
      group: "{{ group|default('root') }}"
      mode: "{{ fileMode|default('644') }}"
    loop: "{{ templates_files }}"
    tags:
    - molecule-idempotence-notest

