# processes recursively a given folder and templates all files from source to destination    
# variables:
# - template_source_dir (mandatory)
#     one of the following is mandatory too, either a given destination is used or a random one is created and returned
# - destination_dir: fixed destination, files will be moved there if variable is set
# - dir_var: return parameter with output directory, esp. for random locations
# - title: prefix for the string of the name
# - owner:
# - group:
# - directoryMode:
# - fileMode:

- name: verify if variables are sufficiently defined
  assert:
    that:
    - destination_dir is defined or dir_var is defined
    - template_source_dir is defined
    quiet: true

- block:
  - name: create remote temporary directory
    ansible.builtin.tempfile:
      state: directory
      suffix: "_template_remote"
    register: remote_tmp_dir

  - set_fact:
      templates_dirs:  "{{ lookup('pipe', '[ ! -d \"'+ template_source_dir +'\" ] || find \"'+ template_source_dir +'\"   -type d').split('\n')|reject('match', '^$')  }}"
      templates_files: "{{ lookup('pipe', '[ ! -d \"'+ template_source_dir +'\" ] || find \"'+ template_source_dir +'\" ! -type d').split('\n')|reject('match', '^$')  }}"
      "{{ dir_var|default('foo') }}": "{{ remote_tmp_dir.path }}"
      dest_dir: "{{ remote_tmp_dir.path }}"

  - name: "{{ title | default('') }} ensure destination directories exist for templates"
    become: no
    file:
      path: "{{ remote_tmp_dir.path }}/{{ item | relpath(template_source_dir) }}"
      recurse: true
      state: directory
      owner: "{{ owner|default('root') }}"
      group: "{{ group|default('root') }}"
      mode: "{{ directoryMode|default('755') }}"
    loop: "{{ templates_dirs }}"

  - name: render templates locally
    become: no
    template:
      src: "{{ item }}"
      dest: "{{ remote_tmp_dir.path }}/{{ item | relpath(template_source_dir) }}"
      owner: "{{ owner|default('root') }}"
      group: "{{ group|default('root') }}"
      mode: "{{ fileMode|default('644') }}"
    loop: "{{ templates_files }}"

  - name: move files to final destination
    copy:
      src: "{{ remote_tmp_dir.path }}/"
      dest: "{{ destination_dir }}"
      remote_src: yes
    when: destination_dir is defined
